### ISSUE TITLE
No released version

### ISSUE THREAD

**Issue by mgrojo** [jrmarino/zstd-ada#1]
Hi,

There isn't any release nor tagged version. Is this library ready for production use in its current state?

Best wishes

**Comment by jrmarino** [comment]
As far as I know.
It was built against one of the first releases of zstd, but it should still work.  I haven't worked on this code in a couple of years though, so I can't say if anything got obsoleted by later zstd changes though.

**Comment by mgrojo** [comment]
Ok, I meant a release of zstd-ada itself, but knowing with which versions of zstd has been tested would also be useful.

Just to report back, I compiled the master branch against libzstd 1.4.4 and the streaming_compress demo is working, although it surprised me that it is slower than gzip.  I guess the problem is about how the file is read, not zstd itself.

In any case, I think I'm not finally using your binding because I only need to import `ZSTD_compress` and `ZSTD_decompress` but in a different way than yours. I want to pass a System.Address where a `void *` is used for `src` and `dst`. In this way I plan to compress directly a memory buffer.
